name: Dispatched Event Workflow

on:
    repository_dispatch:
        types:
            - bot-webhook

jobs:
    run_js_script:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 14 # Choose the desired Node.js version

            - name: Run JavaScript Script
              run: |

                  echo ${{ toJson(github.event.client_payload.data) }}

                  # Execute your JavaScript script here
                  node script/commit.js ${{ toJson(github.event.client_payload.data) }}
