name: Dispatched Event Workflow

on:
  repository_dispatch:
    types:
      - bot-webhook

concurrency:
  group: "bot-webhook"
  cancel-in-progress: false

jobs:
  run_js_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # Choose the desired Node.js version

      - name: Run JavaScript Script
        env:
          payload_data: ${{ toJson(github.event.client_payload) }}
        run: |
          # Execute your JavaScript script here
          node script/commit.js

      - name: Commit Files
        uses: EndBug/add-and-commit@v7
        with:
          author_name: GitHub Actions
          message: "action(auto): add new package"

  build:
    needs: run_js_script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: ./deploy.yaml
